// Code generated by MockGen. DO NOT EDIT.
// Source: ./strategy.go
//
// Generated by this command:
//
//	mockgen -source=./strategy.go -destination=./mock/mock_strategy.go
//

// Package mock_strategy is a generated GoMock package.
package mock_strategy

import (
	context "context"
	reflect "reflect"

	broker "github.com/gobenpark/cerebro/broker"
	indicator "github.com/gobenpark/cerebro/indicator"
	item "github.com/gobenpark/cerebro/item"
	order "github.com/gobenpark/cerebro/order"
	risk "github.com/gobenpark/cerebro/risk"
	strategy "github.com/gobenpark/cerebro/strategy"
	gomock "go.uber.org/mock/gomock"
)

// MockStrategy is a mock of Strategy interface.
type MockStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyMockRecorder
	isgomock struct{}
}

// MockStrategyMockRecorder is the mock recorder for MockStrategy.
type MockStrategyMockRecorder struct {
	mock *MockStrategy
}

// NewMockStrategy creates a new mock instance.
func NewMockStrategy(ctrl *gomock.Controller) *MockStrategy {
	mock := &MockStrategy{ctrl: ctrl}
	mock.recorder = &MockStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategy) EXPECT() *MockStrategyMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockStrategy) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockStrategyMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockStrategy)(nil).Name))
}

// NotifyFund mocks base method.
func (m *MockStrategy) NotifyFund() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyFund")
}

// NotifyFund indicates an expected call of NotifyFund.
func (mr *MockStrategyMockRecorder) NotifyFund() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyFund", reflect.TypeOf((*MockStrategy)(nil).NotifyFund))
}

// NotifyOrder mocks base method.
func (m *MockStrategy) NotifyOrder(o order.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyOrder", o)
}

// NotifyOrder indicates an expected call of NotifyOrder.
func (mr *MockStrategyMockRecorder) NotifyOrder(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrder", reflect.TypeOf((*MockStrategy)(nil).NotifyOrder), o)
}

// NotifyTrade mocks base method.
func (m *MockStrategy) NotifyTrade() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyTrade")
}

// NotifyTrade indicates an expected call of NotifyTrade.
func (mr *MockStrategyMockRecorder) NotifyTrade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyTrade", reflect.TypeOf((*MockStrategy)(nil).NotifyTrade))
}

// Run mocks base method.
func (m *MockStrategy) Run(ctx context.Context, u strategy.Universe, b broker.Submitter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx, u, b)
}

// Run indicates an expected call of Run.
func (mr *MockStrategyMockRecorder) Run(ctx, u, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockStrategy)(nil).Run), ctx, u, b)
}

// MockRiskAware is a mock of RiskAware interface.
type MockRiskAware struct {
	ctrl     *gomock.Controller
	recorder *MockRiskAwareMockRecorder
	isgomock struct{}
}

// MockRiskAwareMockRecorder is the mock recorder for MockRiskAware.
type MockRiskAwareMockRecorder struct {
	mock *MockRiskAware
}

// NewMockRiskAware creates a new mock instance.
func NewMockRiskAware(ctrl *gomock.Controller) *MockRiskAware {
	mock := &MockRiskAware{ctrl: ctrl}
	mock.recorder = &MockRiskAwareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRiskAware) EXPECT() *MockRiskAwareMockRecorder {
	return m.recorder
}

// ExitPolicy mocks base method.
func (m *MockRiskAware) ExitPolicy() risk.Policy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitPolicy")
	ret0, _ := ret[0].(risk.Policy)
	return ret0
}

// ExitPolicy indicates an expected call of ExitPolicy.
func (mr *MockRiskAwareMockRecorder) ExitPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitPolicy", reflect.TypeOf((*MockRiskAware)(nil).ExitPolicy))
}

// Name mocks base method.
func (m *MockRiskAware) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockRiskAwareMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockRiskAware)(nil).Name))
}

// NotifyFund mocks base method.
func (m *MockRiskAware) NotifyFund() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyFund")
}

// NotifyFund indicates an expected call of NotifyFund.
func (mr *MockRiskAwareMockRecorder) NotifyFund() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyFund", reflect.TypeOf((*MockRiskAware)(nil).NotifyFund))
}

// NotifyOrder mocks base method.
func (m *MockRiskAware) NotifyOrder(o order.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyOrder", o)
}

// NotifyOrder indicates an expected call of NotifyOrder.
func (mr *MockRiskAwareMockRecorder) NotifyOrder(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrder", reflect.TypeOf((*MockRiskAware)(nil).NotifyOrder), o)
}

// NotifyTrade mocks base method.
func (m *MockRiskAware) NotifyTrade() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyTrade")
}

// NotifyTrade indicates an expected call of NotifyTrade.
func (mr *MockRiskAwareMockRecorder) NotifyTrade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyTrade", reflect.TypeOf((*MockRiskAware)(nil).NotifyTrade))
}

// Run mocks base method.
func (m *MockRiskAware) Run(ctx context.Context, u strategy.Universe, b broker.Submitter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx, u, b)
}

// Run indicates an expected call of Run.
func (mr *MockRiskAwareMockRecorder) Run(ctx, u, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRiskAware)(nil).Run), ctx, u, b)
}

// MockUniverse is a mock of Universe interface.
type MockUniverse struct {
	ctrl     *gomock.Controller
	recorder *MockUniverseMockRecorder
	isgomock struct{}
}

// MockUniverseMockRecorder is the mock recorder for MockUniverse.
type MockUniverseMockRecorder struct {
	mock *MockUniverse
}

// NewMockUniverse creates a new mock instance.
func NewMockUniverse(ctrl *gomock.Controller) *MockUniverse {
	mock := &MockUniverse{ctrl: ctrl}
	mock.recorder = &MockUniverseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniverse) EXPECT() *MockUniverseMockRecorder {
	return m.recorder
}

// Items mocks base method.
func (m *MockUniverse) Items() []*item.Item {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Items")
	ret0, _ := ret[0].([]*item.Item)
	return ret0
}

// Items indicates an expected call of Items.
func (mr *MockUniverseMockRecorder) Items() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Items", reflect.TypeOf((*MockUniverse)(nil).Items))
}

// OrderBooks mocks base method.
func (m *MockUniverse) OrderBooks() <-chan indicator.OrderBook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderBooks")
	ret0, _ := ret[0].(<-chan indicator.OrderBook)
	return ret0
}

// OrderBooks indicates an expected call of OrderBooks.
func (mr *MockUniverseMockRecorder) OrderBooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderBooks", reflect.TypeOf((*MockUniverse)(nil).OrderBooks))
}

// Ticks mocks base method.
func (m *MockUniverse) Ticks() <-chan indicator.Tick {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ticks")
	ret0, _ := ret[0].(<-chan indicator.Tick)
	return ret0
}

// Ticks indicates an expected call of Ticks.
func (mr *MockUniverseMockRecorder) Ticks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ticks", reflect.TypeOf((*MockUniverse)(nil).Ticks))
}
