// Code generated by MockGen. DO NOT EDIT.
// Source: ./market.go
//
// Generated by this command:
//
//	mockgen -source=./market.go -destination=./mock/mock_market.go
//

// Package mock_market is a generated GoMock package.
package mock_market

import (
	context "context"
	reflect "reflect"

	indicator "github.com/gobenpark/cerebro/indicator"
	item "github.com/gobenpark/cerebro/item"
	market "github.com/gobenpark/cerebro/market"
	order "github.com/gobenpark/cerebro/order"
	position "github.com/gobenpark/cerebro/position"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockMarket is a mock of Market interface.
type MockMarket struct {
	ctrl     *gomock.Controller
	recorder *MockMarketMockRecorder
	isgomock struct{}
}

// MockMarketMockRecorder is the mock recorder for MockMarket.
type MockMarketMockRecorder struct {
	mock *MockMarket
}

// NewMockMarket creates a new mock instance.
func NewMockMarket(ctrl *gomock.Controller) *MockMarket {
	mock := &MockMarket{ctrl: ctrl}
	mock.recorder = &MockMarketMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarket) EXPECT() *MockMarketMockRecorder {
	return m.recorder
}

// AccountBalance mocks base method.
func (m *MockMarket) AccountBalance() decimal.Decimal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountBalance")
	ret0, _ := ret[0].(decimal.Decimal)
	return ret0
}

// AccountBalance indicates an expected call of AccountBalance.
func (mr *MockMarketMockRecorder) AccountBalance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountBalance", reflect.TypeOf((*MockMarket)(nil).AccountBalance))
}

// AccountPositions mocks base method.
func (m *MockMarket) AccountPositions() []position.Position {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountPositions")
	ret0, _ := ret[0].([]position.Position)
	return ret0
}

// AccountPositions indicates an expected call of AccountPositions.
func (mr *MockMarketMockRecorder) AccountPositions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountPositions", reflect.TypeOf((*MockMarket)(nil).AccountPositions))
}

// Candles mocks base method.
func (m *MockMarket) Candles(ctx context.Context, code string, level market.CandleType) (indicator.Candles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Candles", ctx, code, level)
	ret0, _ := ret[0].(indicator.Candles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Candles indicates an expected call of Candles.
func (mr *MockMarketMockRecorder) Candles(ctx, code, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Candles", reflect.TypeOf((*MockMarket)(nil).Candles), ctx, code, level)
}

// Commission mocks base method.
func (m *MockMarket) Commission() decimal.Decimal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commission")
	ret0, _ := ret[0].(decimal.Decimal)
	return ret0
}

// Commission indicates an expected call of Commission.
func (mr *MockMarketMockRecorder) Commission() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commission", reflect.TypeOf((*MockMarket)(nil).Commission))
}

// Events mocks base method.
func (m *MockMarket) Events(ctx context.Context) <-chan any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx)
	ret0, _ := ret[0].(<-chan any)
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockMarketMockRecorder) Events(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockMarket)(nil).Events), ctx)
}

// Order mocks base method.
func (m *MockMarket) Order(ctx context.Context, o order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Order", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Order indicates an expected call of Order.
func (mr *MockMarketMockRecorder) Order(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Order", reflect.TypeOf((*MockMarket)(nil).Order), ctx, o)
}

// Stocks mocks base method.
func (m *MockMarket) Stocks(ctx context.Context) []*item.Item {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stocks", ctx)
	ret0, _ := ret[0].([]*item.Item)
	return ret0
}

// Stocks indicates an expected call of Stocks.
func (mr *MockMarketMockRecorder) Stocks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stocks", reflect.TypeOf((*MockMarket)(nil).Stocks), ctx)
}

// Subscribe mocks base method.
func (m *MockMarket) Subscribe(handler market.TickEventHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockMarketMockRecorder) Subscribe(handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMarket)(nil).Subscribe), handler)
}
